doc-warnings: yes
test-warnings: no
strictness: veryhigh
max-line-length: 120
uses:
  - django
pep8:
  full: true
  options:
    max-line-length: 79
pylint:
  run: true
mccabe:
  run: true
autodetect: yes
requirements:
  - requirements.txt
