doc-warnings: yes
test-warnings: no
strictness: veryhigh
uses:
  - django
pep8:
  full: true
pylint:
  run: true
vulture:
  run: true
mccabe:
  run: true
autodetect: yes
requirements:
  - requirements.txt
